import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ConditionalNavigation } from '@/components/organisms/conditionalNavigation';
import Footer from '@/components/organisms/footer';
import { ThemeProvider } from '@/context/ThemeContext';
import ThemeToggle from '@/components/atoms/themeToggle';
import { SpeedInsights } from '@vercel/speed-insights/next';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Florian Kuehne Fullstack Developer',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  // Inline script to set theme before React hydrates (prevents flash)
  const themeScript = `
    (function() {
      const stored = localStorage.getItem('theme-preference');
      let theme = stored;
      if (!theme) {
        theme = window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
      }
      document.documentElement.setAttribute('data-theme', theme);
    })();
  `;

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
            <ConditionalNavigation />
            <Footer />
          </NextIntlClientProvider>
          <ThemeToggle />
        </ThemeProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
